// Theme customization manifest.
//
// Each scaffolded project ships a `theme.manifest.ts` (overlaid by the
// theme it was scaffolded from) declaring which fields the admin UI
// should expose. Different themes can expose different fields — a
// minimal theme might only allow color tweaks, a richer theme might
// expose logo / hero image / per-section typography.
//
// Override values are stored in KvStore under
//   PK = `siteconfig:{siteId}`, SK = `theme.{field.key}`
// and propagated to the public site through the normal site-settings
// S3 cache. See docs/THEMES.md for authoring details.

export type ThemeFieldType =
  | 'color'
  | 'text'
  | 'select'
  | 'image'
  | 'length'
  | 'fontFamily'
  | 'linkList'

/**
 * Single entry in a `linkList` field. Stored as part of a JSON array
 * under the field's storage key. `url` may be:
 *  - a relative path (`/about`)
 *  - an absolute URL (`https://example.com`)
 *  - a tag reference (`tag:guide`) — themes interpret this as
 *    "expand to a list of posts with this tag" rather than rendering
 *    a literal link.
 */
export interface LinkListItem {
  label: string
  url: string
}

/**
 * A user-facing string in a manifest. Either a plain string (rendered
 * as-is, regardless of locale) or a per-locale map (the renderer picks
 * the active locale, falling back to `en`, then to any value).
 *
 * Themes that ship in a single language can keep these as plain
 * strings. The default themes use the map form so the same manifest
 * works for both built-in dictionaries.
 */
export type LocalizedString = string | Record<string, string>

interface ThemeFieldBase {
  /** Storage key. Persisted as `theme.{key}` in site settings. */
  key: string
  label: LocalizedString
  description?: LocalizedString
  /** Optional UI grouping (e.g. 'Colors', 'Typography', 'Branding'). */
  group?: LocalizedString
  /** Used when no override is set. Always a string for storage uniformity. */
  default: string
  /**
   * If set, the loader injects `${cssVar}: ${value}` into a `:root`
   * style block on every public page, so CSS rules using
   * `var(${cssVar})` pick up overrides at render time.
   *
   * Fields without `cssVar` (e.g. logo URL, header tagline) are exposed
   * to template code via `loadThemeConfig()` instead.
   */
  cssVar?: string
}

export interface ThemeColorField extends ThemeFieldBase {
  type: 'color'
}

export interface ThemeTextField extends ThemeFieldBase {
  type: 'text'
  maxLength?: number
}

export interface ThemeSelectField extends ThemeFieldBase {
  type: 'select'
  options: ReadonlyArray<{ value: string; label: LocalizedString }>
}

export interface ThemeImageField extends ThemeFieldBase {
  type: 'image'
}

export interface ThemeLengthField extends ThemeFieldBase {
  type: 'length'
}

export interface ThemeFontFamilyField extends ThemeFieldBase {
  type: 'fontFamily'
  options: ReadonlyArray<{ value: string; label: LocalizedString }>
}

/**
 * A repeatable list of {label, url} entries — used for nav menus,
 * footer link sets, sidebar groups, etc. Stored in KvStore as a JSON
 * string so it fits the existing `string`-valued site-settings cache.
 *
 * `default` is declared as a plain array for ergonomics; the loader
 * stringifies it on the fly so manifest authors don't have to call
 * JSON.stringify by hand.
 */
export interface ThemeLinkListField extends Omit<ThemeFieldBase, 'default' | 'cssVar'> {
  type: 'linkList'
  default: ReadonlyArray<LinkListItem>
  /** Cap admin-supplied list length. Default 50. */
  maxItems?: number
}

export type ThemeField =
  | ThemeColorField
  | ThemeTextField
  | ThemeSelectField
  | ThemeImageField
  | ThemeLengthField
  | ThemeFontFamilyField
  | ThemeLinkListField

export interface ThemeManifest {
  /** Theme directory name (`themes/<name>/`). */
  name: string
  label: LocalizedString
  description?: LocalizedString
  fields: ReadonlyArray<ThemeField>
}

export function defineTheme(m: ThemeManifest): ThemeManifest {
  return m
}

/**
 * Resolve a `LocalizedString` to a plain string for display.
 * Strings pass through; maps pick `locale` → `fallback` → any value
 * → empty. The empty fallback keeps the renderer from crashing on a
 * malformed manifest while making the missing translation visible.
 */
export function resolveLocalized(
  value: LocalizedString | undefined,
  locale: string,
  fallback: string = 'en'
): string {
  if (value === undefined) return ''
  if (typeof value === 'string') return value
  return value[locale] ?? value[fallback] ?? Object.values(value)[0] ?? ''
}

// --- Theme module (multi-theme runtime selection) ---
//
// A scaffolded project ships every installed theme under
//   `themes/<name>/index.ts`
// Each `index.ts` does `export default defineThemeModule({ ... })`.
//
// The `themes-registry.ts` file (generated by create-ampless) imports
// each module and exposes the map. The active theme is stored as
// `theme.active` in site settings; the public dispatcher reads it
// per-site, so different siteIds can render different themes against
// the same scaffold.
//
// Page components are typed loosely as `unknown` here because Next.js
// page-component prop types vary by route shape. Themes implement them
// as server components matching the dispatcher's `params` Promise type.
export interface ThemeRouteContext<P = Record<string, string>> {
  params: Promise<P & { siteId: string }>
}

export interface ThemeModule {
  /** Stable identifier — must match the directory name and the value
   *  stored as `theme.active`. */
  name: string
  manifest: ThemeManifest
  /**
   * Server components rendered by the dispatcher routes under
   * `app/site/[siteId]/`. Each theme MUST provide Home; Post / Tag are
   * recommended but optional (dispatcher 404s when missing).
   */
  components: {
    Home: (ctx: ThemeRouteContext) => Promise<unknown> | unknown
    Post?: (ctx: ThemeRouteContext<{ slug: string }>) => Promise<unknown> | unknown
    Tag?: (ctx: ThemeRouteContext<{ tag: string }>) => Promise<unknown> | unknown
  }
  /**
   * Optional `generateMetadata` hooks called by the dispatcher. Same
   * signature as the matching component's params.
   */
  metadata?: {
    Home?: (ctx: ThemeRouteContext) => Promise<unknown> | unknown
    Post?: (ctx: ThemeRouteContext<{ slug: string }>) => Promise<unknown> | unknown
    Tag?: (ctx: ThemeRouteContext<{ tag: string }>) => Promise<unknown> | unknown
  }
  /**
   * Optional route handlers for /feed.xml and /sitemap.xml. The
   * dispatcher returns 404 if a theme doesn't provide them.
   */
  routes?: {
    feed?: (ctx: { siteId: string; request: Request }) => Promise<Response>
    sitemap?: (ctx: { siteId: string; request: Request }) => Promise<Response>
  }
}

// Returns the broad ThemeModule type (not a narrowed T) so the registry's
// `themes[name]` indexing always sees a uniform surface — without this,
// a module that omits `metadata.Home` produces a narrow type where
// `Home` literally doesn't exist as a property, breaking dispatchers
// that probe optional methods generically.
export function defineThemeModule(m: ThemeModule): ThemeModule {
  return m
}

/**
 * Storage key used in KvStore. Prefix `theme.` keeps the namespace
 * separate from `site.*` / `media.*` so unrelated tools can scan
 * settings without colliding.
 */
export function themeSettingKey(fieldKey: string): string {
  return `theme.${fieldKey}`
}

const COLOR_RE =
  /^(#[0-9a-fA-F]{3,8}|rgb\([^)]+\)|rgba\([^)]+\)|hsl\([^)]+\)|hsla\([^)]+\)|oklch\([^)]+\)|oklab\([^)]+\))$/
const LENGTH_RE = /^[\d.]+(px|rem|em|%|vh|vw)$/
const IMAGE_URL_RE = /^(https?:\/\/[^\s]+|\/[^\s]*)$/

/**
 * Reject malformed or potentially-injectable values before they reach
 * the KvStore. Admin/editor are trusted but typos and copy-paste
 * mistakes shouldn't be able to break a site's CSS or sneak `</style>`
 * into the inline tag the loader emits.
 *
 * Returns the normalized value, or null if the input is rejected.
 */
export function validateThemeValue(field: ThemeField, raw: unknown): string | null {
  if (field.type === 'linkList') return validateLinkListValue(field, raw)
  if (typeof raw !== 'string') return null
  const v = raw.trim()
  if (!v) return null
  switch (field.type) {
    case 'color':
      return COLOR_RE.test(v) ? v : null
    case 'length':
      return LENGTH_RE.test(v) ? v : null
    case 'image':
      return IMAGE_URL_RE.test(v) ? v : null
    case 'select':
    case 'fontFamily':
      return field.options.some((o) => o.value === v) ? v : null
    case 'text': {
      const max = (field as ThemeTextField).maxLength ?? 200
      // Strip control chars + angle brackets so values inserted into HTML
      // attributes / inline styles can't escape their context.
      const sanitized = v.replace(/[\x00-\x1f<>]/g, '')
      return sanitized.length <= max ? sanitized : sanitized.slice(0, max)
    }
  }
}

const URL_RE =
  /^(https?:\/\/[^\s]+|\/[^\s]*|tag:[^\s]+|mailto:[^\s]+|tel:[^\s]+|#[^\s]*)$/

function validateLinkListValue(field: ThemeLinkListField, raw: unknown): string | null {
  if (typeof raw !== 'string') return null
  const trimmed = raw.trim()
  if (!trimmed) return JSON.stringify([])
  let parsed: unknown
  try {
    parsed = JSON.parse(trimmed)
  } catch {
    return null
  }
  if (!Array.isArray(parsed)) return null
  const max = field.maxItems ?? 50
  if (parsed.length > max) return null
  const cleaned: LinkListItem[] = []
  for (const entry of parsed) {
    if (!entry || typeof entry !== 'object') continue
    const e = entry as Record<string, unknown>
    const label = typeof e.label === 'string' ? e.label.replace(/[\x00-\x1f<>]/g, '').trim().slice(0, 120) : ''
    const url = typeof e.url === 'string' ? e.url.trim().slice(0, 500) : ''
    if (!label || !url) continue
    if (!URL_RE.test(url)) continue
    cleaned.push({ label, url })
  }
  return JSON.stringify(cleaned)
}

/** Parse a stored linkList JSON value into typed items. Tolerant: bad
 *  shapes resolve to []. Throwing here would cascade into rendering. */
export function parseLinkList(raw: string | undefined | null): LinkListItem[] {
  if (!raw) return []
  try {
    const parsed = JSON.parse(raw)
    if (!Array.isArray(parsed)) return []
    return parsed
      .filter((e): e is LinkListItem =>
        !!e &&
        typeof e === 'object' &&
        typeof (e as { label: unknown }).label === 'string' &&
        typeof (e as { url: unknown }).url === 'string'
      )
      .map((e) => ({ label: e.label, url: e.url }))
  } catch {
    return []
  }
}

export function stringifyLinkList(items: ReadonlyArray<LinkListItem>): string {
  return JSON.stringify(items.map((i) => ({ label: i.label, url: i.url })))
}

/**
 * Detect a `tag:<name>` URL form. Themes use this to render a list of
 * posts under a heading instead of a literal link — useful for docs
 * sidebars and category-style nav.
 */
export function isTagListUrl(url: string): { tag: string } | null {
  const m = /^tag:(.+)$/.exec(url.trim())
  if (!m) return null
  const tag = m[1]!.trim()
  return tag ? { tag } : null
}

/**
 * Resolve effective values for every manifest field, merging stored
 * overrides on top of defaults. `stored` is the flat settings map keyed
 * by `theme.{key}` — typically the output of `listSiteSettings(siteId)`
 * filtered to theme entries.
 */
export function resolveThemeValues(
  manifest: ThemeManifest,
  stored: Record<string, unknown>
): Record<string, string> {
  const out: Record<string, string> = {}
  for (const field of manifest.fields) {
    const storeKey = themeSettingKey(field.key)
    const raw = stored[storeKey]
    const validated = raw !== undefined ? validateThemeValue(field, raw) : null
    out[field.key] = validated ?? defaultValueAsString(field)
  }
  return out
}

/**
 * Manifest field defaults are typed differently per field — most are
 * plain strings (color, length, text, etc.), but `linkList` defaults
 * are arrays for ergonomics. Normalize both to the storage form
 * (always a string) so consumers see one shape.
 */
function defaultValueAsString(field: ThemeField): string {
  if (field.type === 'linkList') return stringifyLinkList(field.default)
  return field.default
}
