// Theme customization manifest.
//
// Each scaffolded project ships a `theme.manifest.ts` (overlaid by the
// theme it was scaffolded from) declaring which fields the admin UI
// should expose. Different themes can expose different fields — a
// minimal theme might only allow color tweaks, a richer theme might
// expose logo / hero image / per-section typography.
//
// Override values are stored in KvStore under
//   PK = `siteconfig`, SK = `theme.{field.key}`
// and propagated to the public site through the normal site-settings
// S3 cache. See docs/THEMES.md for authoring details.

export type ThemeFieldType =
  | 'color'
  | 'text'
  | 'select'
  | 'image'
  | 'length'
  | 'fontFamily'
  | 'linkList'

/**
 * Single entry in a `linkList` field. Stored as part of a JSON array
 * under the field's storage key. `url` may be:
 *  - a relative path (`/about`)
 *  - an absolute URL (`https://example.com`)
 *  - a tag reference (`tag:guide`) — themes interpret this as
 *    "expand to a list of posts with this tag" rather than rendering
 *    a literal link.
 */
export interface LinkListItem {
  label: string
  url: string
}

/**
 * A user-facing string in a manifest. Either a plain string (rendered
 * as-is, regardless of locale) or a per-locale map (the renderer picks
 * the active locale, falling back to `en`, then to any value).
 *
 * Themes that ship in a single language can keep these as plain
 * strings. The default themes use the map form so the same manifest
 * works for both built-in dictionaries.
 */
export type LocalizedString = string | Record<string, string>

interface ThemeFieldBase {
  /** Storage key. Persisted as `theme.{key}` in site settings. */
  key: string
  label: LocalizedString
  description?: LocalizedString
  /** Optional UI grouping (e.g. 'Colors', 'Typography', 'Branding'). */
  group?: LocalizedString
  /** Used when no override is set. Always a string for storage uniformity. */
  default: string
  /**
   * If set, the loader injects `${cssVar}: ${value}` into a `:root`
   * style block on every public page, so CSS rules using
   * `var(${cssVar})` pick up overrides at render time.
   *
   * Fields without `cssVar` (e.g. logo URL, header tagline) are exposed
   * to template code via `loadThemeConfig()` instead.
   */
  cssVar?: string
}

export interface ThemeColorField extends ThemeFieldBase {
  type: 'color'
}

export interface ThemeTextField extends ThemeFieldBase {
  type: 'text'
  maxLength?: number
}

export interface ThemeSelectField extends ThemeFieldBase {
  type: 'select'
  options: ReadonlyArray<{ value: string; label: LocalizedString }>
}

export interface ThemeImageField extends ThemeFieldBase {
  type: 'image'
}

export interface ThemeLengthField extends ThemeFieldBase {
  type: 'length'
}

export interface ThemeFontFamilyField extends ThemeFieldBase {
  type: 'fontFamily'
  options: ReadonlyArray<{ value: string; label: LocalizedString }>
}

/**
 * A repeatable list of {label, url} entries — used for nav menus,
 * footer link sets, sidebar groups, etc. Stored in KvStore as a JSON
 * string so it fits the existing `string`-valued site-settings cache.
 *
 * `default` is declared as a plain array for ergonomics; the loader
 * stringifies it on the fly so manifest authors don't have to call
 * JSON.stringify by hand.
 */
export interface ThemeLinkListField extends Omit<ThemeFieldBase, 'default' | 'cssVar'> {
  type: 'linkList'
  default: ReadonlyArray<LinkListItem>
  /** Cap admin-supplied list length. Default 50. */
  maxItems?: number
}

export type ThemeField =
  | ThemeColorField
  | ThemeTextField
  | ThemeSelectField
  | ThemeImageField
  | ThemeLengthField
  | ThemeFontFamilyField
  | ThemeLinkListField

export interface ThemeManifest {
  /** Theme directory name (`themes/<name>/`). */
  name: string
  label: LocalizedString
  description?: LocalizedString
  fields: ReadonlyArray<ThemeField>
}

export function defineTheme(m: ThemeManifest): ThemeManifest {
  return m
}

/**
 * Resolve a `LocalizedString` to a plain string for display.
 * Strings pass through; maps pick `locale` → `fallback` → any value
 * → empty. The empty fallback keeps the renderer from crashing on a
 * malformed manifest while making the missing translation visible.
 */
export function resolveLocalized(
  value: LocalizedString | undefined,
  locale: string,
  fallback: string = 'en'
): string {
  if (value === undefined) return ''
  if (typeof value === 'string') return value
  return value[locale] ?? value[fallback] ?? Object.values(value)[0] ?? ''
}

// --- Theme module (multi-theme runtime selection) ---
//
// A scaffolded project ships every installed theme under
//   `themes/<name>/index.ts`
// Each `index.ts` does `export default defineThemeModule({ ... })`.
//
// The `themes-registry.ts` file (generated by create-ampless) imports
// each module and exposes the map. The active theme is stored as
// `theme.active` in site settings; the public dispatcher reads it from
// the cached settings on each request.
//
// Page components are typed loosely as `unknown` here because Next.js
// page-component prop types vary by route shape. Themes implement them
// as server components matching the dispatcher's `params` Promise type.
//
// The dispatcher routes live under `app/site/[siteId]/...` for internal
// reasons (URL flattening is a separate change); `[siteId]` is always
// resolved to a constant `'default'` and not surfaced in public URLs.
// The param is preserved on `ThemeRouteContext` so existing dispatcher
// signatures (which forward `params` straight to themes) still type-check.
export interface ThemeRouteContext<P = Record<string, string>> {
  params: Promise<P & { siteId: string }>
}

export interface ThemeModule {
  /** Stable identifier — must match the directory name and the value
   *  stored as `theme.active`. */
  name: string
  manifest: ThemeManifest
  /**
   * Server components rendered by the dispatcher routes under
   * `app/site/[siteId]/`. Each theme MUST provide Home; Post / Tag are
   * recommended but optional (dispatcher 404s when missing).
   */
  components: {
    Home: (ctx: ThemeRouteContext) => Promise<unknown> | unknown
    Post?: (ctx: ThemeRouteContext<{ slug: string }>) => Promise<unknown> | unknown
    Tag?: (ctx: ThemeRouteContext<{ tag: string }>) => Promise<unknown> | unknown
  }
  /**
   * Optional `generateMetadata` hooks called by the dispatcher. Same
   * signature as the matching component's params.
   */
  metadata?: {
    Home?: (ctx: ThemeRouteContext) => Promise<unknown> | unknown
    Post?: (ctx: ThemeRouteContext<{ slug: string }>) => Promise<unknown> | unknown
    Tag?: (ctx: ThemeRouteContext<{ tag: string }>) => Promise<unknown> | unknown
  }
  /**
   * Optional route handlers for /feed.xml and /sitemap.xml. The
   * dispatcher returns 404 if a theme doesn't provide them.
   */
  routes?: {
    feed?: (ctx: { request: Request }) => Promise<Response>
    sitemap?: (ctx: { request: Request }) => Promise<Response>
  }
}

// Returns the broad ThemeModule type (not a narrowed T) so the registry's
// `themes[name]` indexing always sees a uniform surface — without this,
// a module that omits `metadata.Home` produces a narrow type where
// `Home` literally doesn't exist as a property, breaking dispatchers
// that probe optional methods generically.
export function defineThemeModule(m: ThemeModule): ThemeModule {
  return m
}

/**
 * Storage key used in KvStore. Prefix `theme.` keeps the namespace
 * separate from `site.*` / `media.*` so unrelated tools can scan
 * settings without colliding.
 */
export function themeSettingKey(fieldKey: string): string {
  return `theme.${fieldKey}`
}

const COLOR_RE =
  /^(#[0-9a-fA-F]{3,8}|rgb\([^)]+\)|rgba\([^)]+\)|hsl\([^)]+\)|hsla\([^)]+\)|oklch\([^)]+\)|oklab\([^)]+\))$/
const LENGTH_RE = /^[\d.]+(px|rem|em|%|vh|vw)$/
// Image src: same denylist approach as linkList — block schemes the
// browser would treat as script execution, accept everything else
// (relative paths, http(s), data:image/... for inline base64). Image
// elements never execute javascript: URLs even if we let them through,
// but rejecting them up front keeps the stored values clean.
const DANGEROUS_IMAGE_URL_RE = /^\s*(javascript|vbscript):/i

/**
 * Reject malformed or potentially-injectable values before they reach
 * the KvStore. Admin/editor are trusted but typos and copy-paste
 * mistakes shouldn't be able to break a site's CSS or sneak `</style>`
 * into the inline tag the loader emits.
 *
 * Returns the normalized value, or null if the input is rejected.
 */
/**
 * Split a stored color value into its light / dark components.
 *
 * Accepts two storage forms:
 *   - Single value: `oklch(...)` / `#abcdef` / etc. → `{ light: value, dark: null }`
 *   - Pair: `light-dark(L, D)` → `{ light: L, dark: D }`
 *
 * Splits on the top-level comma (depth-aware) so nested commas inside
 * `rgb(...)` / `hsl(...)` don't trip the parser.
 */
export function parseColorPair(value: string): { light: string; dark: string | null } {
  const v = value.trim()
  const prefix = 'light-dark('
  if (!v.startsWith(prefix) || !v.endsWith(')')) {
    return { light: value, dark: null }
  }
  const inner = v.slice(prefix.length, -1)
  let depth = 0
  for (let i = 0; i < inner.length; i++) {
    const ch = inner[i]
    if (ch === '(') depth++
    else if (ch === ')') depth--
    else if (ch === ',' && depth === 0) {
      return {
        light: inner.slice(0, i).trim(),
        dark: inner.slice(i + 1).trim(),
      }
    }
  }
  // Malformed: no top-level comma. Treat the whole thing as single.
  return { light: value, dark: null }
}

/**
 * Build the storage string for a color field. When `dark` is non-empty
 * and differs from `light`, returns `light-dark(light, dark)`; otherwise
 * returns the bare `light` value. The runtime emits the result verbatim
 * into the inline `:root { --foo: <value> }` override; `light-dark()`
 * is a Baseline-2024 CSS function so the browser picks per mode.
 */
export function formatColorPair(light: string, dark?: string | null): string {
  const l = light.trim()
  const d = (dark ?? '').trim()
  if (!d || d === l) return l
  return `light-dark(${l}, ${d})`
}

export function validateThemeValue(field: ThemeField, raw: unknown): string | null {
  if (field.type === 'linkList') return validateLinkListValue(field, raw)
  if (typeof raw !== 'string') return null
  const v = raw.trim()
  if (!v) return null
  switch (field.type) {
    case 'color': {
      // Color fields accept either a single CSS color or a
      // `light-dark(L, D)` pair where each component is itself a valid
      // CSS color. The renderer pastes the result verbatim into a
      // `:root { --foo: <value> }` override, so any malformed input
      // (including nested `light-dark()` or non-color args) must be
      // rejected up front.
      if (v.startsWith('light-dark(')) {
        const { light, dark } = parseColorPair(v)
        if (dark === null) return null
        if (!COLOR_RE.test(light) || !COLOR_RE.test(dark)) return null
        return formatColorPair(light, dark)
      }
      return COLOR_RE.test(v) ? v : null
    }
    case 'length':
      return LENGTH_RE.test(v) ? v : null
    case 'image':
      return DANGEROUS_IMAGE_URL_RE.test(v) ? null : v
    case 'select':
    case 'fontFamily':
      return field.options.some((o) => o.value === v) ? v : null
    case 'text': {
      const max = (field as ThemeTextField).maxLength ?? 200
      // Strip control chars + angle brackets so values inserted into HTML
      // attributes / inline styles can't escape their context.
      const sanitized = v.replace(/[\x00-\x1f<>]/g, '')
      return sanitized.length <= max ? sanitized : sanitized.slice(0, max)
    }
  }
}

// Drop URLs that the browser would treat as a script execution
// channel. Everything else — relative paths, bare domains, tag: refs,
// mailto:, anchors — passes through and gets rendered as-is.
const DANGEROUS_URL_RE = /^\s*(javascript|data|vbscript):/i

function validateLinkListValue(field: ThemeLinkListField, raw: unknown): string | null {
  // Accept three input shapes:
  //   1. A JSON-string (admin form / fresh writes go through here).
  //   2. An already-parsed array (the S3 settings cache can land here
  //      depending on how AWSJSON round-trips through DynamoDB; we'd
  //      rather coerce than reject and silently fall back to default).
  //   3. null / undefined / "" — treat as empty list.
  let parsed: unknown
  if (Array.isArray(raw)) {
    parsed = raw
  } else if (typeof raw === 'string') {
    const trimmed = raw.trim()
    if (!trimmed) return JSON.stringify([])
    try {
      parsed = JSON.parse(trimmed)
    } catch {
      return null
    }
  } else if (raw === null || raw === undefined) {
    return JSON.stringify([])
  } else {
    return null
  }
  if (!Array.isArray(parsed)) return null
  const max = field.maxItems ?? 50
  if (parsed.length > max) return null
  const cleaned: LinkListItem[] = []
  for (const entry of parsed) {
    if (!entry || typeof entry !== 'object') continue
    const e = entry as Record<string, unknown>
    const rawLabel = typeof e.label === 'string' ? e.label : ''
    const rawUrl = typeof e.url === 'string' ? e.url : ''
    const label = rawLabel.replace(/[\x00-\x1f<>]/g, '').trim().slice(0, 120)
    const url = rawUrl.replace(/[\x00-\x1f]/g, '').trim().slice(0, 500)
    // Drop only fully-empty rows. Keep partial rows so admins can save
    // mid-edit without their in-progress work disappearing — they'll
    // come back and finish later.
    if (!label && !url) continue
    if (url && DANGEROUS_URL_RE.test(url)) continue
    cleaned.push({ label, url })
  }
  return JSON.stringify(cleaned)
}

/** Parse a stored linkList JSON value into typed items. Tolerant: bad
 *  shapes resolve to []. Throwing here would cascade into rendering. */
export function parseLinkList(raw: string | undefined | null): LinkListItem[] {
  if (!raw) return []
  try {
    const parsed = JSON.parse(raw)
    if (!Array.isArray(parsed)) return []
    return parsed
      .filter((e): e is LinkListItem =>
        !!e &&
        typeof e === 'object' &&
        typeof (e as { label: unknown }).label === 'string' &&
        typeof (e as { url: unknown }).url === 'string'
      )
      .map((e) => ({ label: e.label, url: e.url }))
  } catch {
    return []
  }
}

export function stringifyLinkList(items: ReadonlyArray<LinkListItem>): string {
  return JSON.stringify(items.map((i) => ({ label: i.label, url: i.url })))
}

/**
 * Detect a `tag:<name>` URL form. Themes use this to render a list of
 * posts under a heading instead of a literal link — useful for docs
 * sidebars and category-style nav.
 */
export function isTagListUrl(url: string): { tag: string } | null {
  const m = /^tag:(.+)$/.exec(url.trim())
  if (!m) return null
  const tag = m[1]!.trim()
  return tag ? { tag } : null
}

/**
 * Resolve effective values for every manifest field, merging stored
 * overrides on top of defaults. `stored` is the flat settings map keyed
 * by `theme.{key}` — typically the output of `listSiteSettings()`
 * filtered to theme entries.
 */
export function resolveThemeValues(
  manifest: ThemeManifest,
  stored: Record<string, unknown>
): Record<string, string> {
  const out: Record<string, string> = {}
  for (const field of manifest.fields) {
    const storeKey = themeSettingKey(field.key)
    const raw = stored[storeKey]
    const validated = raw !== undefined ? validateThemeValue(field, raw) : null
    out[field.key] = validated ?? defaultValueAsString(field)
  }
  return out
}

/**
 * Manifest field defaults are typed differently per field — most are
 * plain strings (color, length, text, etc.), but `linkList` defaults
 * are arrays for ergonomics. Normalize both to the storage form
 * (always a string) so consumers see one shape.
 */
function defaultValueAsString(field: ThemeField): string {
  if (field.type === 'linkList') return stringifyLinkList(field.default)
  return field.default
}
