// Generated by `npx create-ampless setup-encryption-key`.
// AES-256-GCM key (32 bytes, base64) for plugin secret storage.
// Rotate via the same CLI command. Existing ciphertext becomes unreadable on rotation.
//
// IMPORTANT: This is a placeholder. Replace the value below with a real key
// by running: npx create-ampless setup-encryption-key
// (from your project root, after scaffolding).

export const PLUGIN_SECRET_ENCRYPTION_KEY = ''
