'use client'

// Registration store for tiptap-node → HTML adapters that first-party
// plugins (e.g. `@ampless/plugin-youtube/editor`) export so the admin's
// "format: tiptap → html" body switch can losslessly serialise embed
// nodes to the canonical placeholder div form. Templates wire it up once in
// `_editor-bootstrap.tsx` (generated by `update-ampless`):
//
//   'use client'
//   import { installAdminEditorExtensions, installAdminTiptapNodeMarkdown, installAdminTiptapNodeHtml } from '@ampless/admin/editor'
//   import * as __ampless_plugin_youtube_editor from '@ampless/plugin-youtube/editor'
//   import * as __ampless_plugin_x_embed_editor from '@ampless/plugin-x-embed/editor'
//
//   export function EditorBootstrap({ children }: { children: React.ReactNode }) {
//     installAdminEditorExtensions([
//       __ampless_plugin_youtube_editor.editorExtension,
//       __ampless_plugin_x_embed_editor.editorExtension,
//     ])
//     installAdminTiptapNodeMarkdown([
//       __ampless_plugin_youtube_editor.tiptapNodeToMarkdown ?? {},
//       __ampless_plugin_x_embed_editor.tiptapNodeToMarkdown ?? {},
//     ])
//     installAdminTiptapNodeHtml([
//       __ampless_plugin_youtube_editor.tiptapNodeToHtml ?? {},
//       __ampless_plugin_x_embed_editor.tiptapNodeToHtml ?? {},
//     ])
//     return <>{children}</>
//   }
//
// Then thread `<EditorBootstrap>` into `createAdminLayout(admin, {
// editorBootstrap: EditorBootstrap })`. The adapters are passed as an
// **array of maps** (not a pre-merged object) so the install can detect
// cross-plugin nodeType collisions — see `installAdminTiptapNodeHtml`
// below.

import type { TiptapNodeHtmlAdapters } from 'ampless'

let adapters: Record<string, (node: any) => string | null> = {}
let installed = false

/**
 * Installs tiptap-node → HTML adapters into the admin runtime.
 * Called once at admin bootstrap from the `update-ampless`-generated
 * `_editor-bootstrap.tsx` — see plugin author guide.
 *
 * Idempotent: subsequent calls after the first are no-ops (= HMR /
 * double-mount safe).
 *
 * **Takes an array of maps, one per plugin** (NOT a single pre-merged
 * object). Pre-merging via object spread (`{ ...a, ...b }`) would
 * silently lose cross-plugin collisions because a JS object literal
 * can't carry duplicate keys at all — the last spread wins quietly.
 * By keeping the plugin maps separate, the install can detect when two
 * plugins register **different** adapter functions for the same
 * `nodeType` and throw at bootstrap time, instead of producing
 * hard-to-diagnose silent round-trip failures at format-switch time.
 *
 * Same-plugin re-occurrences (= same `nodeType` registered with the
 * **identical** function reference, e.g. the same plugin's map appearing
 * twice from idempotent codegen) are allowed — the second occurrence is
 * a no-op.
 */
export function installAdminTiptapNodeHtml(
  maps: ReadonlyArray<TiptapNodeHtmlAdapters>,
): void {
  if (installed) return
  for (const map of maps) {
    for (const [type, adapter] of Object.entries(map)) {
      if (type in adapters && adapters[type] !== adapter) {
        throw new Error(
          `installAdminTiptapNodeHtml: conflict on nodeType "${type}" — two plugins registered different adapter functions`,
        )
      }
      adapters[type] = adapter
    }
  }
  installed = true
}

/**
 * Read the currently installed tiptap-node → HTML adapters.
 * `post-form.tsx` calls this when switching format `tiptap → html` or
 * `markdown → html` and passes the result as `{ nodeAdapters }` to
 * `tiptapToHtml`. The map is intentionally readonly — consumers should not
 * mutate it.
 */
export function getAdminTiptapNodeHtml(): TiptapNodeHtmlAdapters {
  return adapters
}
