'use client'

// Registration store for tiptap-node → markdown adapters that first-party
// plugins (e.g. `@ampless/plugin-youtube/editor`) export so the admin's
// "format: tiptap → markdown" body switch can losslessly serialise embed
// nodes back to bare URL lines. Templates wire it up once in
// `_editor-bootstrap.tsx` (generated by `update-ampless`):
//
//   'use client'
//   import { installAdminEditorExtensions, installAdminTiptapNodeMarkdown } from '@ampless/admin/editor'
//   import * as __ampless_plugin_youtube_editor from '@ampless/plugin-youtube/editor'
//
//   export function EditorBootstrap({ children }: { children: React.ReactNode }) {
//     installAdminEditorExtensions([
//       __ampless_plugin_youtube_editor.editorExtension,
//     ])
//     installAdminTiptapNodeMarkdown({
//       ...(__ampless_plugin_youtube_editor.tiptapNodeToMarkdown ?? {}),
//     })
//     return <>{children}</>
//   }
//
// Then thread `<EditorBootstrap>` into `createAdminLayout(admin, {
// editorBootstrap: EditorBootstrap })`.

import type { TiptapNodeMarkdownAdapters } from 'ampless'

let adapters: Record<string, (node: any) => string | null> = {}
let installed = false

/**
 * Installs tiptap-node → markdown adapters into the admin runtime.
 * Called once at admin bootstrap from the `update-ampless`-generated
 * `_editor-bootstrap.tsx` — see plugin author guide.
 *
 * Idempotent: subsequent calls after the first are no-ops (= HMR /
 * double-mount safe).
 *
 * Collision detection: throws when two **different** adapter functions
 * are registered for the same nodeType. This surfaces misconfiguration
 * early (at bootstrap time) rather than silently keeping the last
 * registered adapter and producing hard-to-diagnose round-trip failures.
 */
export function installAdminTiptapNodeMarkdown(map: TiptapNodeMarkdownAdapters): void {
  if (installed) return
  for (const [type, adapter] of Object.entries(map)) {
    if (type in adapters && adapters[type] !== adapter) {
      throw new Error(
        `installAdminTiptapNodeMarkdown: conflict on nodeType "${type}" — two different adapter functions registered`,
      )
    }
    adapters[type] = adapter
  }
  installed = true
}

/**
 * Read the currently installed tiptap-node → markdown adapters.
 * `post-form.tsx` calls this when switching format `tiptap → markdown`
 * and passes the result as `{ nodeAdapters }` to `tiptapToMarkdown`.
 * The map is intentionally readonly — consumers should not mutate it.
 */
export function getAdminTiptapNodeMarkdown(): TiptapNodeMarkdownAdapters {
  return adapters
}
