import { createCipheriv, randomBytes } from 'node:crypto'
import type { Handler } from 'aws-lambda'
import { DynamoDBClient, PutItemCommand, DeleteItemCommand } from '@aws-sdk/client-dynamodb'
import { marshall } from '@aws-sdk/util-dynamodb'
import { isValidPluginKey, validatePluginSettingValue } from 'ampless'

// AppSync Lambda handler backing the `setPluginSecret` and
// `clearPluginSecret` mutations (Phase 6a v2.2).
//
// Security model:
//   - The browser sends plaintext to AppSync (TLS in transit).
//   - This Lambda validates group membership, enforces field constraints,
//     reads the AES-256-GCM key from process.env.PLUGIN_SECRET_ENCRYPTION_KEY
//     (injected by CDK from the value in amplify/secrets/encryption-key.ts),
//     encrypts, and writes only the ciphertext to DynamoDB. The plaintext
//     is never written to disk.
//   - Admin/editor Cognito users have NO direct AppSync access to the
//     PluginSecret table (IAM-only authorization on that model).
//   - The return value of both mutations is a plain success/error string —
//     never the ciphertext or any secret material.
//
// Ciphertext format (base64-encoded):
//   IV[12] || ciphertext || authTag[16]
// This is the same layout that the trusted-processor decryptSecret()
// function and the admin-side tests expect.
//
// Key source: PLUGIN_SECRET_ENCRYPTION_KEY env var (base64, 32 bytes).
// Generated by: `npx create-ampless setup-encryption-key`
// Stored in: amplify/secrets/encryption-key.ts (adjacent to backend.ts)

const ddb = new DynamoDBClient({})

const ADMIN_GROUP = 'ampless-admin'
const EDITOR_GROUP = 'ampless-editor'

function requireEnv(name: string): string {
  const v = process.env[name]
  if (!v) throw new Error(`plugin-secret-handler: missing required env var ${name}`)
  return v
}

// ---------------------------------------------------------------------------
// Encryption key — read from process.env at module-load time (v2.2).
//
// Decoded once at cold start; any Lambda invocation reuses the same Buffer.
// Fail-fast: if the env var is absent or malformed, throw immediately so
// the misconfiguration is caught at deploy time (Lambda health check) rather
// than silently on the first secret-save operation.
// ---------------------------------------------------------------------------
const _encKeyB64 = process.env.PLUGIN_SECRET_ENCRYPTION_KEY
if (!_encKeyB64) {
  throw new Error(
    '[plugin-secret-handler] PLUGIN_SECRET_ENCRYPTION_KEY env var is not set. ' +
      'Run `npx create-ampless setup-encryption-key` and configure ' +
      'pluginSecretEncryptionKey in defineAmplessBackend().'
  )
}
const _encKeyBuf = Buffer.from(_encKeyB64, 'base64')
if (_encKeyBuf.byteLength !== 32) {
  throw new Error(
    `[plugin-secret-handler] PLUGIN_SECRET_ENCRYPTION_KEY must encode 32 bytes ` +
      `(got ${_encKeyBuf.byteLength}). Re-run \`npx create-ampless setup-encryption-key\`.`
  )
}
const ENCRYPTION_KEY: Buffer = _encKeyBuf

function getEncryptionKey(): Buffer {
  return ENCRYPTION_KEY
}

/**
 * Encrypt `plaintext` with AES-256-GCM.
 * Returns base64( IV[12] || ciphertext || authTag[16] ).
 * Node.js `createCipheriv` produces ciphertext and authTag separately;
 * we concatenate them after the IV.
 */
export function encryptSecret(rawKey: Buffer, plaintext: string): string {
  const iv = randomBytes(12)
  const cipher = createCipheriv('aes-256-gcm', rawKey, iv)
  const encrypted = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()])
  const authTag = cipher.getAuthTag()
  const combined = Buffer.concat([iv, encrypted, authTag])
  return combined.toString('base64')
}

/**
 * Build the DynamoDB sort key. Mirrors processor-trusted.ts and
 * plugin-secret.ts (admin lib) so all three callers use the same format.
 *   sk = `plugins.${instanceId}.${fieldKey}`
 */
function pluginSecretSk(instanceId: string, fieldKey: string): string {
  return `plugins.${instanceId}.${fieldKey}`
}

// ---------------------------------------------------------------------------
// Event shape for Amplify Gen 2 `a.handler.function()` mutations.
// Same shape as user-admin.ts: Amplify wraps the arguments in a flat
// payload, not the canonical AppSyncResolverEvent (which has event.info).
// ---------------------------------------------------------------------------

interface SetArgs {
  fieldKey: string
  instanceId: string
  value: string
}

interface ClearArgs {
  fieldKey: string
  instanceId: string
}

interface PluginSecretHandlerEvent {
  typeName: string
  fieldName: string
  arguments: Partial<SetArgs & ClearArgs>
  // identity is the Cognito user token / IAM role context set by AppSync.
  // When a Cognito user calls via AppSync, identity is:
  //   { sub, username, groups: [...], ... }
  identity?: {
    sub?: string
    username?: string
    groups?: string[]
    [k: string]: unknown
  }
}

function isAllowedGroup(identity: PluginSecretHandlerEvent['identity']): boolean {
  const groups = identity?.groups ?? []
  return groups.includes(ADMIN_GROUP) || groups.includes(EDITOR_GROUP)
}

async function handleSet(args: SetArgs): Promise<string> {
  const { fieldKey, instanceId, value } = args

  if (!isValidPluginKey(instanceId)) {
    throw new Error(`[plugin-secret-handler] Invalid instanceId: "${instanceId}"`)
  }
  if (!isValidPluginKey(fieldKey)) {
    throw new Error(`[plugin-secret-handler] Invalid fieldKey: "${fieldKey}"`)
  }
  if (typeof value !== 'string') {
    throw new Error('[plugin-secret-handler] value must be a string')
  }

  // Validate against a loose text-field descriptor. PluginSecretField
  // is always type 'text' or 'textarea' — we cannot know the exact field
  // definition here (it lives in the plugin manifest, not the request
  // payload), so we apply the universal safety rules:
  //   - Strip control chars + angle brackets (same as validatePluginSettingValue).
  //   - Enforce a 10 000-char hard cap to prevent outsized DDB items.
  // Individual field-level constraints (maxLength, pattern, required)
  // are also enforced client-side in the admin lib before the mutation
  // call, providing fast UX feedback. If the client skips that check
  // the server-side cap here still protects the database.
  const validated = validatePluginSettingValue(
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    { type: 'text', key: fieldKey, label: fieldKey, maxLength: 10000 } as any,
    value,
    'strict'
  )
  if (validated === null) {
    throw new Error(
      `[plugin-secret-handler] Value for field "${fieldKey}" failed validation (too long or contains invalid characters).`
    )
  }
  const sanitizedValue = validated as string

  // Encrypt the sanitized plaintext with the key from the env var.
  const encKey = getEncryptionKey()
  const ciphertext = encryptSecret(encKey, sanitizedValue)

  const sk = pluginSecretSk(instanceId, fieldKey)
  const secretTable = requireEnv('AMPLESS_PLUGIN_SECRET_TABLE')
  const indicatorTable = requireEnv('AMPLESS_PLUGIN_SECRET_INDICATOR_TABLE')
  const now = new Date().toISOString()

  // Write ciphertext to PluginSecret.
  await ddb.send(
    new PutItemCommand({
      TableName: secretTable,
      Item: marshall({ sk, value: ciphertext }),
    })
  )

  // Write existence indicator to PluginSecretIndicator.
  await ddb.send(
    new PutItemCommand({
      TableName: indicatorTable,
      Item: marshall({ sk, lastSetAt: now }),
    })
  )

  return 'ok'
}

async function handleClear(args: ClearArgs): Promise<string> {
  const { fieldKey, instanceId } = args

  if (!isValidPluginKey(instanceId)) {
    throw new Error(`[plugin-secret-handler] Invalid instanceId: "${instanceId}"`)
  }
  if (!isValidPluginKey(fieldKey)) {
    throw new Error(`[plugin-secret-handler] Invalid fieldKey: "${fieldKey}"`)
  }

  const sk = pluginSecretSk(instanceId, fieldKey)
  const secretTable = requireEnv('AMPLESS_PLUGIN_SECRET_TABLE')
  const indicatorTable = requireEnv('AMPLESS_PLUGIN_SECRET_INDICATOR_TABLE')

  // Delete from PluginSecret (no-op if row does not exist).
  await ddb.send(
    new DeleteItemCommand({
      TableName: secretTable,
      Key: marshall({ sk }),
    })
  )

  // Delete from PluginSecretIndicator.
  await ddb.send(
    new DeleteItemCommand({
      TableName: indicatorTable,
      Key: marshall({ sk }),
    })
  )

  return 'ok'
}

export const handler: Handler<PluginSecretHandlerEvent, string | null> = async (event) => {
  const field = event.fieldName

  // Re-check Cognito group membership. AppSync enforces the
  // `.authorization` rule before invoking this Lambda, but an explicit
  // re-check here means the Lambda is safe even if invoked directly
  // (e.g. a misconfigured IAM policy that lets a principal call Lambda
  // bypassing AppSync). Belt-and-suspenders.
  if (!isAllowedGroup(event.identity)) {
    console.error(
      `[plugin-secret-handler] ${field}: caller is not in admin or editor group`,
      { identity: event.identity }
    )
    throw new Error('Unauthorized: caller must be in ampless-admin or ampless-editor group')
  }

  try {
    if (field === 'setPluginSecret') {
      const { fieldKey, instanceId, value } = event.arguments as SetArgs
      if (!fieldKey || !instanceId || value === undefined) {
        throw new Error('[plugin-secret-handler] setPluginSecret: missing required arguments')
      }
      return await handleSet({ fieldKey, instanceId, value })
    }

    if (field === 'clearPluginSecret') {
      const { fieldKey, instanceId } = event.arguments as ClearArgs
      if (!fieldKey || !instanceId) {
        throw new Error('[plugin-secret-handler] clearPluginSecret: missing required arguments')
      }
      return await handleClear({ fieldKey, instanceId })
    }

    console.error(`[plugin-secret-handler] unsupported fieldName: ${field}`)
    throw new Error(`Unsupported fieldName: ${field}`)
  } catch (err) {
    console.error(`[plugin-secret-handler] ${field} failed:`, err)
    throw err
  }
}
