// Shape of `amplify_outputs.json` (generated by `ampx sandbox` / deploy)
// that the runtime cares about. Fields are declared loosely — the
// runtime narrows what it needs at call sites, and templates can pass
// the full file through without remapping.

export interface StorageOutput {
  bucket_name: string
  aws_region: string
}

export interface DataOutput {
  url: string
  aws_region: string
  default_authorization_type?: string
  api_key?: string
  // ...additional fields present in real amplify_outputs.json
}

export interface AmplessOutputs {
  storage?: StorageOutput
  data?: DataOutput
  // pass-through shape — keep open-ended so templates can hand the
  // whole file in without losing fields the runtime hasn't formalized.
  [key: string]: unknown
}
