import { cp, readFile, writeFile, readdir, mkdir, rm } from 'fs/promises'
import { join, extname, resolve } from 'path'
import { templatePath } from './templates.js'
import { DEFAULT_GITIGNORE } from './gitignore.js'
import type { ProjectOptions } from './prompts.js'

const TEXT_EXTENSIONS = new Set([
  '.json', '.md', '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.html', '.css', '.env', '.txt', '.yaml', '.yml', '.toml', '.gitignore',
])

async function substituteFile(filePath: string, vars: Record<string, string>): Promise<void> {
  const ext = extname(filePath) || filePath.endsWith('.gitignore') ? '.gitignore' : ''
  if (!TEXT_EXTENSIONS.has(ext)) return

  const content = await readFile(filePath, 'utf-8')
  const replaced = content.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] ?? `{{${key}}}`)
  if (replaced !== content) await writeFile(filePath, replaced, 'utf-8')
}

async function substituteDir(dirPath: string, vars: Record<string, string>): Promise<void> {
  const entries = await readdir(dirPath, { withFileTypes: true })
  await Promise.all(
    entries.map(async (entry) => {
      const fullPath = join(dirPath, entry.name)
      if (entry.isDirectory()) {
        await substituteDir(fullPath, vars)
      } else {
        await substituteFile(fullPath, vars)
      }
    })
  )
}

/**
 * Generate `themes-registry.ts` content listing every installed theme.
 * Always overwrites whatever the shared base shipped, so the runtime
 * registry exactly matches what was actually copied under `themes/`.
 *
 * Adding a theme later = drop a directory under `themes/<name>/`, edit
 * this file by hand to add the import + map entry, redeploy.
 */
function buildRegistry(themes: string[]): string {
  const imports = themes.map((t) => `import ${t} from '@/themes/${t}'`).join('\n')
  const map = themes.map((t) => `  ${t},`).join('\n')
  return `// Generated by create-ampless. Lists every theme installed under
// \`themes/<name>/\`. Adding a theme = drop a directory under themes/,
// add an import + map entry below, and redeploy.
//
// \`theme.active\` (per-site, in KvStore) picks which theme renders for
// each request; everything listed here gets bundled so switching is
// instant.

${imports}

export const themes = {
${map}
} as const

export type ThemeName = keyof typeof themes

export const themeList = Object.values(themes)

export const DEFAULT_THEME: ThemeName = (themeList[0]?.name as ThemeName) ?? '${themes[0]}'
`
}

/**
 * Scaffold a new project from a shared base + multi-theme overlay.
 *
 * 1. Copy the shared base (`templates/_shared/`) — admin app, amplify
 *    backend, lib, ui components, middleware, cms.config defaults, etc.
 * 2. Copy every selected theme to `<dest>/themes/<name>/`. Themes ship
 *    self-contained (manifest, pages, tokens.css); the dispatcher in
 *    _shared imports them through the generated registry.
 * 3. Generate `themes-registry.ts` listing the installed themes — this
 *    overwrites the placeholder _shared shipped, so the bundle matches
 *    exactly what's on disk.
 * 4. Run `{{var}}` substitution on every text file in the result.
 */
export async function scaffold(
  sharedDir: string,
  themesRoot: string,
  destDir: string,
  opts: ProjectOptions
): Promise<void> {
  await cp(sharedDir, destDir, { recursive: true })

  // Copy each selected theme into <dest>/themes/<name>/
  const destThemesDir = resolve(destDir, 'themes')
  await rm(destThemesDir, { recursive: true, force: true })
  await mkdir(destThemesDir, { recursive: true })
  for (const theme of opts.themes) {
    const src = templatePath(theme)
    const dst = resolve(destThemesDir, theme)
    await cp(src, dst, { recursive: true })
  }
  // `themesRoot` is unused for now (every theme resolves via templatePath),
  // but the parameter keeps the signature ready for future per-theme
  // resolution strategies (e.g. installing community themes from npm).
  void themesRoot

  // Overwrite the shared themes-registry.ts with the actually-installed list.
  const registryPath = resolve(destDir, 'themes-registry.ts')
  await writeFile(registryPath, buildRegistry(opts.themes), 'utf-8')

  // Write the canonical `.gitignore` (generated from a constant rather
  // than shipped in `templates/_shared/` to dodge npm's nested-dotfile
  // packing quirks). Always overwrites, so the scaffold's notion of
  // "what should never be committed" wins over any stale template.
  const gitignorePath = resolve(destDir, '.gitignore')
  await writeFile(gitignorePath, DEFAULT_GITIGNORE, 'utf-8')

  const vars: Record<string, string> = {
    projectName: opts.projectName,
    siteName: opts.siteName,
    year: String(new Date().getFullYear()),
    plugins: JSON.stringify(opts.plugins),
    themes: JSON.stringify(opts.themes),
    defaultTheme: opts.defaultTheme,
  }

  await substituteDir(destDir, vars)
}
