/**
 * `npx create-ampless setup-encryption-key`
 *
 * Generates the AES-256-GCM encryption key for plugin secret storage and
 * writes it to `amplify/secrets/encryption-key.ts` (adjacent to
 * `amplify/backend.ts`). No AWS credentials required — this is a local
 * file operation only.
 *
 * The user's `amplify/backend.ts` imports the constant from the file and
 * passes it to `defineAmplessBackend({ pluginSecretEncryptionKey: ... })`,
 * which injects it into the Lambda env vars via CDK at deploy time.
 *
 * Threat model:
 *   ✓ AWS Console operator browsing DDB sees ciphertext only (key not in DDB)
 *   ⚠ Anyone with source repo / deploy artifact access can decrypt
 *     → keep the repo private OR use --gitignore and distribute the key separately
 *   ✗ Malicious trusted plugin in the same Lambda can read process.env
 *     → true isolation = per-plugin Lambda (privileged tier, roadmap)
 *
 * Key rotation:
 *   Re-run this command and confirm overwrite. Existing ciphertext in DDB
 *   becomes unreadable; re-save each secret via /admin/plugins.
 */

import { writeFile, mkdir, readFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'
import { randomBytes } from 'node:crypto'
import { log, confirm, outro, cancel } from '@clack/prompts'
import pc from 'picocolors'
import type { ParsedArgs } from './args.js'

// ---------------------------------------------------------------------------
// File path + content template
// ---------------------------------------------------------------------------

const SECRETS_DIR = 'amplify/secrets'
const KEY_FILE = 'encryption-key.ts'
const KEY_FILE_PATH = `${SECRETS_DIR}/${KEY_FILE}`

function buildFileContent(keyB64: string): string {
  return (
    `// Generated by \`npx create-ampless setup-encryption-key\`.\n` +
    `// AES-256-GCM key (32 bytes, base64) for plugin secret storage.\n` +
    `// Rotate via the same CLI command. Existing ciphertext becomes unreadable on rotation.\n` +
    `\n` +
    `export const PLUGIN_SECRET_ENCRYPTION_KEY = '${keyB64}'\n`
  )
}

function extractKeyValue(source: string): string | null {
  const match = source.match(
    /\bPLUGIN_SECRET_ENCRYPTION_KEY\b\s*(?::\s*[^=]+)?=\s*(['"])(.*?)\1/
  )
  return match?.[2] ?? null
}

function isEmptyPlaceholder(source: string): boolean {
  return extractKeyValue(source) === ''
}

// ---------------------------------------------------------------------------
// .gitignore helper
// ---------------------------------------------------------------------------

async function appendGitignoreEntry(cwd: string, entry: string): Promise<void> {
  const gitignorePath = join(cwd, '.gitignore')
  if (existsSync(gitignorePath)) {
    const content = await readFile(gitignorePath, 'utf-8')
    if (content.includes(entry)) return // already present
    await writeFile(gitignorePath, content + (content.endsWith('\n') ? '' : '\n') + entry + '\n')
  } else {
    await writeFile(gitignorePath, entry + '\n')
  }
}

// ---------------------------------------------------------------------------
// Main command
// ---------------------------------------------------------------------------

export async function runSetupEncryptionKey(args: ParsedArgs): Promise<void> {
  const cwd = process.cwd()

  // 1. Verify we are inside an amplify project (amplify/ dir exists).
  if (!existsSync(join(cwd, 'amplify'))) {
    log.error(
      `No \`amplify/\` directory found in ${cwd}.\n` +
        'Run this command from the root of an ampless project (where amplify/backend.ts lives).'
    )
    process.exit(1)
  }

  const keyFilePath = join(cwd, KEY_FILE_PATH)

  // 2. Check for existing key file. Only the scaffolded empty placeholder is
  // safe to overwrite without confirmation. Any non-empty or unrecognized
  // content could be a real key (or a hand-edited variant), so require an
  // explicit rotation confirmation because old ciphertext becomes unreadable.
  if (existsSync(keyFilePath)) {
    const existingContent = await readFile(keyFilePath, 'utf-8')
    if (!isEmptyPlaceholder(existingContent)) {
      log.warn(
        pc.yellow(
          `${KEY_FILE_PATH} already exists.\n` +
            'Overwriting it will make all existing plugin secrets unreadable\n' +
            'until each secret is re-saved through the admin UI.'
        )
      )
      const confirmed = await confirm({
        message: 'Overwrite the existing encryption key?',
        initialValue: false,
      })
      if (confirmed === false || confirmed === undefined) {
        cancel('Cancelled — existing key preserved.')
        return
      }
    }
  }

  // 3. Generate a new 32-byte random key.
  const keyBytes = randomBytes(32)
  const keyB64 = keyBytes.toString('base64')

  // 4. Ensure the amplify/secrets/ directory exists.
  const secretsDir = join(cwd, SECRETS_DIR)
  if (!existsSync(secretsDir)) {
    await mkdir(secretsDir, { recursive: true })
  }

  // 5. Write the key file.
  try {
    await writeFile(keyFilePath, buildFileContent(keyB64), 'utf-8')
  } catch (err) {
    log.error(
      `Failed to write ${KEY_FILE_PATH}: ${err instanceof Error ? err.message : String(err)}`
    )
    process.exit(1)
  }

  // 6. Optionally append to .gitignore.
  if (args.gitignore) {
    try {
      await appendGitignoreEntry(cwd, KEY_FILE_PATH)
      log.info(`Added ${KEY_FILE_PATH} to .gitignore`)
    } catch (err) {
      log.warn(
        `Could not update .gitignore: ${err instanceof Error ? err.message : String(err)}\n` +
          `Add \`${KEY_FILE_PATH}\` to your .gitignore manually.`
      )
    }
  }

  // 7. Done — print instructions + threat model summary.
  outro(
    `${pc.green('✔')} Generated ${pc.cyan(KEY_FILE_PATH)}\n\n` +
      `  ${pc.bold('Next steps:')}\n` +
      `    1. In \`amplify/backend.ts\`, add:\n` +
      `       import { PLUGIN_SECRET_ENCRYPTION_KEY } from './secrets/encryption-key.js'\n` +
      `       defineAmplessBackend({ ..., pluginSecretEncryptionKey: PLUGIN_SECRET_ENCRYPTION_KEY })\n` +
      `    2. Redeploy (or restart the sandbox) to inject the key into Lambda env vars.\n` +
      `    3. Save plugin secrets via the admin UI — they are now encrypted at rest.\n\n` +
      `  ${pc.bold('Threat model summary:')}\n` +
      `    ${pc.green('✓')} AWS Console operator browsing DDB sees ciphertext only\n` +
      `    ${pc.yellow('⚠')} Anyone with source repo / deploy artifact access can decrypt\n` +
      `    ${pc.red('✗')} Malicious trusted plugin in the same Lambda can also decrypt\n` +
      `       (per-plugin Lambda isolation = roadmap)\n\n` +
      (args.gitignore
        ? `  ${pc.dim(`${KEY_FILE_PATH} added to .gitignore.`)}\n\n`
        : `  ${pc.yellow('Tip:')} If committing to a PUBLIC repo, run with --gitignore instead\n` +
          `  and distribute the key separately.\n\n`) +
      `  ${pc.yellow('Rotation:')} Re-run this command and confirm overwrite.\n` +
      `  Existing ciphertext will be unreadable; re-save via /admin/plugins.`
  )
}
