import { readdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Naming convention for user-owned themes. Anything matching this
 * prefix is treated as "owned by the project, never touched by ampless
 * upgrades"; everything else is an ampless-managed default theme that
 * upgrade syncs to the latest template content.
 *
 * Hyphens are allowed inside the suffix (e.g. `my-blog-2024`), but the
 * registry uses a camelCase identifier when emitting the import line —
 * see `toIdentifier`.
 */
export const CUSTOM_THEME_PREFIX = 'my-'

/**
 * Themes are referenced by their directory name (which is also the
 * `name` field declared in `defineThemeModule`). The kebab-case form
 * works as an object key but not as a bare JS identifier, so the
 * generated registry imports under a camelCase alias and indexes the
 * exported map with the kebab-case key:
 *
 *   import myBlog from '@/themes/my-blog'
 *   export const themes = { blog, 'my-blog': myBlog }
 *
 * This keeps the runtime lookup `themes[theme.active]` working with
 * whatever name a custom theme declares.
 */
export function toIdentifier(themeName: string): string {
  // No hyphens → already a valid identifier.
  if (!themeName.includes('-')) return themeName
  // Convert `my-blog-2024` → `myBlog2024`.
  return themeName.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase())
}

/**
 * True if the theme directory name follows the `my-` convention.
 * User-owned themes survive `create-ampless upgrade` untouched; ampless
 * default themes (blog, minimal, …) are resynced to the template on
 * every upgrade so customizations should always live in a `my-*` copy
 * created via `copy-theme`.
 */
export function isCustomTheme(themeName: string): boolean {
  return themeName.startsWith(CUSTOM_THEME_PREFIX)
}

/**
 * Discover every theme installed under `<destDir>/themes/<name>/`.
 * The order is filesystem-dependent; callers that need a stable order
 * should sort the result themselves.
 */
export async function discoverInstalledThemes(destDir: string): Promise<string[]> {
  const themesDir = join(destDir, 'themes')
  if (!existsSync(themesDir)) return []
  const entries = await readdir(themesDir, { withFileTypes: true })
  return entries.filter((e) => e.isDirectory()).map((e) => e.name)
}

/**
 * Build the contents of `themes-registry.ts` for a given list of
 * installed themes. Ampless defaults are listed before custom themes
 * so `DEFAULT_THEME` (which falls back to `themeList[0]`) lands on a
 * shipped theme rather than a user copy whose name happens to sort
 * first.
 */
export function buildRegistry(themes: readonly string[]): string {
  const sorted = [...themes].sort((a, b) => {
    const ca = isCustomTheme(a)
    const cb = isCustomTheme(b)
    if (ca !== cb) return ca ? 1 : -1
    return a.localeCompare(b)
  })

  const imports = sorted.map((t) => `import ${toIdentifier(t)} from '@/themes/${t}'`).join('\n')
  const map = sorted
    .map((t) => {
      const id = toIdentifier(t)
      return id === t ? `  ${t},` : `  '${t}': ${id},`
    })
    .join('\n')
  const fallback = sorted[0] ?? 'blog'

  return `// Generated by create-ampless. Lists every theme installed under
// \`themes/<name>/\`. Auto-managed: \`create-ampless upgrade\` and
// \`copy-theme\` regenerate this file from the directories present
// under \`themes/\`. Edits made by hand will survive only until the
// next upgrade.
//
// \`theme.active\` (per-site, in KvStore) picks which theme renders for
// each request; everything listed here gets bundled so switching is
// instant. Custom themes use the \`${CUSTOM_THEME_PREFIX}\` prefix and
// are never touched by upgrade — clone an ampless default theme into
// a \`${CUSTOM_THEME_PREFIX}<name>\` directory via \`copy-theme\` before
// modifying it.

${imports}

export const themes = {
${map}
} as const

export type ThemeName = keyof typeof themes

export const themeList = Object.values(themes)

/**
 * Default theme used when a site has no \`theme.active\` override.
 * Falls back to the first registered theme so an empty registry would
 * still surface a clear runtime error rather than silent breakage.
 */
export const DEFAULT_THEME: ThemeName = (themeList[0]?.name as ThemeName) ?? '${fallback}'
`
}
