// Generated by create-ampless. Lists every theme installed under
// `themes/<name>/`. Adding a theme = drop a directory under themes/,
// add an import + map entry below, and redeploy.
//
// `theme.active` (per-site, in KvStore) picks which theme renders for
// each request; everything listed here gets bundled so switching is
// instant.
//
// This shared placeholder lists every default theme so the file
// compiles inside _shared/. The scaffold rewrites it at install time
// to import only the themes the user picked.

import blog from '@/themes/blog'
import minimal from '@/themes/minimal'
import landing from '@/themes/landing'
import corporate from '@/themes/corporate'
import docs from '@/themes/docs'
import dads from '@/themes/dads'

export const themes = {
  blog,
  minimal,
  landing,
  corporate,
  docs,
  dads,
} as const

export type ThemeName = keyof typeof themes

export const themeList = Object.values(themes)

/**
 * Default theme used when a site has no `theme.active` override.
 * Falls back to the first registered theme so an empty registry would
 * still surface a clear runtime error rather than silent breakage.
 */
export const DEFAULT_THEME: ThemeName = (themeList[0]?.name as ThemeName) ?? 'blog'
