import outputs from '../../amplify_outputs.json'

export const dynamic = 'force-dynamic'

interface StorageOutput {
  bucket_name: string
  aws_region: string
}

const storage = (outputs as { storage?: StorageOutput }).storage

// /sitemap.xml — proxies the latest sitemap regenerated by plugin-seo to
// `s3://{bucket}/public/plugins/seo/sitemap.xml`. The Lambda hook in
// plugin-seo writes there on every content.published / unpublished /
// deleted event, so we just stream the current version through.
export async function GET() {
  if (!storage) {
    return new Response('Sandbox not deployed', { status: 503 })
  }
  const url = `https://${storage.bucket_name}.s3.${storage.aws_region}.amazonaws.com/public/plugins/seo/sitemap.xml`
  const upstream = await fetch(url, { cache: 'no-store' })
  if (!upstream.ok) {
    // Empty sitemap before any publish has happened — keep crawlers happy.
    return new Response(
      `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>\n`,
      {
        headers: {
          'Content-Type': 'application/xml; charset=utf-8',
          'Cache-Control': 'public, max-age=60',
        },
      }
    )
  }
  return new Response(upstream.body, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=300',
    },
  })
}
